amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 3.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 5000
    min_particles: 1000
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.8
    z_max: 0.05
    z_rand: 0.2
    z_short: 0.05
    scan_topic: scan

    # Initial pose (можно настроить под ваше начальное положение)
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    initial_cov_xx: 0.25
    initial_cov_yy: 0.25
    initial_cov_aa: 0.00685

    

# controller_server:
#   ros__parameters:
#     base_frame_id: "base_footprint"
#     odom_topic: "/odom"
#     global_frame: "map"

# planner_server:
#   ros__parameters:
#     base_frame_id: "base_footprint"
#     global_frame: "map"

# behavior_server:
#   ros__parameters:
#     global_frame: "map"
#     robot_base_frame: "base_footprint"

# bt_navigator:
#   ros__parameters:
#     global_frame: "map"
#     robot_base_frame: "base_footprint"
#     odom_topic: "/odom"